### ISSUE TITLE
Issue setting up TLS on existing gateway

### ISSUE THREAD

**Issue by etknorr** [design-group/traefik-proxy#2]
I used code from #1 to try to set up an existing docker container with TLS encryption. In (this)[https://github.com/design-group/traefik-proxy/tree/step-ca#enabling-tls-for-a-secure-connection-over-tcp] section, would you be able to continue with the example above instead of providing an example for a neo4j graph database?

I have been able to get the service routed through Traefik without TLS, but am having trouble getting my `traefik.tcp.*` labels correct. I feel like I'm really close, but there's definitely a gap in my understanding

To add some background, 
I'm on MacOS, and here are relevant files and screenshots:

### Traefik dashboard:
![image](https://github.com/design-group/traefik-proxy/assets/50336131/c63bc572-98bc-4e41-9afb-896b1c876fdd)

### docker-compose.yml:
```yml
services:
  exchange-resource-dev:
    image: bwdesigngroup/ignition-docker:8.1.25
    hostname: exchange-dev
    ports:
      - 9220:8088
    volumes:
      - ./ignition-data:/workdir
    environment:
      SYMLINK_GITIGNORE: true
      SYMLINK_LOGBACK: false
      TZ: America/Los_Angeles
    command: >
      -n exchange-dev

volumes:
  ignition-data:
```

### docker-compose.traefik.yml:
```yml
services:
  exchange-resource-dev:
    labels:
      traefik.enable: "true"
      traefik.hostname: exchange-resource-dev
      traefik.tcp.routers.ignition.tls: "true"
      traefik.tcp.routers.ignition.rule: "HostSNI(`exchange-resource-dev.localtest.me`)"
      traefik.tcp.routers.ignition.service: "exchange-resource-dev"
      traefik.tcp.services.ignition.loadbalancer.server.port: "9220"
    environment:
      GATEWAY_PUBLIC_HTTPS_PORT: 443
      GATEWAY_PUBLIC_ADDRESS: exchange-resource-dev.localtest.me
    networks:
      - default
      - proxy

networks:
  default:
  proxy:
    external: true
    name: proxy
```
